from enum import Enum

class GlueSprayState(Enum):
    INITIALIZING = "INITIALIZING"
    IDLE = "IDLE"
    STARTED = "STARTED"
    CALIBRATING_ROBOT = "CALIBRATING_ROBOT"
    CALIBRATING_CAMERA = "CALIBRATING_CAMERA"
    MEASURING_HEIGHT = "MEASURING_HEIGHT"
    CREATING_WORKPIECE = "CREATING_WORKPIECE"
    UPDATING_TOOL_CHANGER = "UPDATING_TOOL_CHANGER"
    EXECUTING_TRAJECTORY = "EXECUTING_TRAJECTORY"
    HANDLING_BELT = "HANDLING_BELT"
    TEST_RUNNING = "TEST_RUNNING"
    ERROR = "ERROR"
    PAUSED = "PAUSED"