from enum import Enum

class GlueSprayEvent(Enum):
    # System Events
    SYSTEM_READY = "SYSTEM_READY"
    ROBOT_READY = "ROBOT_READY"
    VISION_READY = "VISION_READY"
    ERROR_OCCURRED = "ERROR_OCCURRED"
    RESET_REQUESTED = "RESET_REQUESTED"

    # Operation Events
    START_REQUESTED = "START_REQUESTED"
    CALIBRATE_ROBOT_REQUESTED = "CALIBRATE_ROBOT_REQUESTED"
    CALIBRATE_CAMERA_REQUESTED = "CALIBRATE_CAMERA_REQUESTED"
    MEASURE_HEIGHT_REQUESTED = "MEASURE_HEIGHT_REQUESTED"
    CREATE_WORKPIECE_REQUESTED = "CREATE_WORKPIECE_REQUESTED"
    UPDATE_TOOL_CHANGER_REQUESTED = "UPDATE_TOOL_CHANGER_REQUESTED"
    EXECUTE_TRAJECTORY_REQUESTED = "EXECUTE_TRAJECTORY_REQUESTED"
    HANDLE_BELT_REQUESTED = "HANDLE_BELT_REQUESTED"
    TEST_RUN_REQUESTED = "TEST_RUN_REQUESTED"

    # Completion Events
    OPERATION_COMPLETED = "OPERATION_COMPLETED"
    OPERATION_FAILED = "OPERATION_FAILED"
    PAUSE_REQUESTED = "PAUSE_REQUESTED"
    RESUME_REQUESTED = "RESUME_REQUESTED"